# Generated by Django 2.2.14 on 2020-08-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20200824_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_full_name', models.CharField(max_length=100)),
                ('years_experience', models.IntegerField()),
                ('qualifications', models.CharField(max_length=500)),
            ],
        ),
    ]
