# Generated by Django 2.2.14 on 2020-08-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_auto_20200826_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='cost_currency',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
