# Generated by Django 2.2.14 on 2020-08-26 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20200826_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
