# Generated by Django 2.2.14 on 2020-08-27 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_instructor_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='cover',
        ),
    ]
