# Generated by Django 2.2.14 on 2020-08-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_comments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lessons.Comment'),
            preserve_default=False,
        ),
    ]
