# Generated by Django 2.2.14 on 2020-08-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_reviews_review_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='review_comments',
        ),
    ]
