# Generated by Django 2.2.14 on 2020-08-27 12:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_remove_reviews_review_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
