# Generated by Django 2.2.14 on 2020-08-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0020_auto_20200827_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='education_level',
            field=models.CharField(choices=[('lower_primary', 'Lower Primary'), ('upper_primary', 'Upper Primary'), ('lower_secondary', 'Lower Secondary'), ('upper_secondary', 'Upper Secondary'), ('junior_college', 'JC')], default='junior_college', max_length=100),
        ),
    ]
