# Generated by Django 2.2.14 on 2020-08-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_auto_20200828_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='syllabus',
            field=models.CharField(choices=[('psle', 'PSLE'), ('o_level', 'GCSE O Level'), ('a_level', 'GCSE A Level')], default='a_level', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tags',
            field=models.CharField(choices=[('primary_math', 'Primary Mathematics'), ('a_math', 'Additional Mathematics'), ('e_math', 'Elementary Mathematics'), ('h1_math', 'H1 Mathematics'), ('h2_math', 'H2 Mathematics')], default='h2_math', max_length=100),
        ),
    ]
