# Generated by Django 2.2.14 on 2020-08-27 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0022_auto_20200828_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='education_level',
            field=models.CharField(choices=[('lower_primary', 'Lower Primary'), ('upper_primary', 'Upper Primary'), ('lower_secondary', 'Lower Secondary'), ('upper_secondary', 'Upper Secondary'), ('junior_college', 'JC')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='syllabus',
            field=models.CharField(choices=[('psle', 'PSLE'), ('o_level', 'GCSE O Level'), ('a_level', 'GCSE A Level')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tags',
            field=models.CharField(choices=[('primary_math', 'Primary Mathematics'), ('a_math', 'Additional Mathematics'), ('e_math', 'Elementary Mathematics'), ('h1_math', 'H1 Mathematics'), ('h2_math', 'H2 Mathematics')], max_length=100),
        ),
    ]
