# Generated by Django 2.2.14 on 2020-08-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0025_auto_20200828_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='education_level',
            field=models.CharField(choices=[('Lower Primary', 'Lower Primary'), ('Upper Primary', 'Upper Primary'), ('Lower Secondary', 'Lower Secondary'), ('Upper Secondary', 'Upper Secondary'), ('Junior College', 'JC')], default='Junior College', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='syllabus',
            field=models.CharField(choices=[('PSLE', 'PSLE'), ('O Level', 'GCSE O Level'), ('A Level', 'GCSE A Level')], default='A Level', max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tags',
            field=models.CharField(choices=[('Primary Math', 'Primary Mathematics'), ('Additional Math', 'Additional Mathematics'), ('Elementary Math', 'Elementary Mathematics'), ('H1 Math', 'H1 Mathematics'), ('H2 Math', 'H2 Mathematics')], default='H2_math', max_length=100),
        ),
    ]
