# Generated by Django 2.2.14 on 2020-08-28 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0027_instructor_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
