# Generated by Django 2.2.14 on 2020-08-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0028_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='tags',
            field=models.CharField(choices=[('Primary Math', 'Primary Mathematics'), ('Additional Math', 'Additional Mathematics'), ('Elementary Math', 'Elementary Mathematics'), ('H1 Math', 'H1 Mathematics'), ('H2 Math', 'H2 Mathematics')], default='H2 Math', max_length=100),
        ),
    ]
