# Generated by Django 2.2.14 on 2020-08-29 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0031_auto_20200829_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentforum',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='commentforum',
            name='full_name',
        ),
        migrations.AddField(
            model_name='commentforum',
            name='commentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
