# Generated by Django 2.2.14 on 2020-08-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0032_auto_20200829_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentForum',
        ),
    ]
